import { Roboto } from 'next/font/google';
import './globals.css';
// 1. import `ChakraProvider` component
import { ChakraProvider } from '@chakra-ui/react';

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '400', '700'] });

export const metadata = {
  title: 'Taskboard',
  description: 'Generated by Pirate',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
